apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-application-controller
  namespace: kuberbank

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-application-controller-role
  namespace: kuberbank
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-application-controller-binding
  namespace: kuberbank
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-application-controller-role
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: argocd
