apiVersion: v1
kind: Namespace
metadata:
  name: kuberbank
  labels:
    name: kuberbank
    environment: production
    monitoring: enabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    environment: production
