apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuberbank-frontend-ingress
  namespace: kuberbank
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "5m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - kuberbank.io
        - www.kuberbank.io
      secretName: kuberbank-frontend-tls
  rules:
    - host: kuberbank.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kuberbank-frontend-service
                port:
                  number: 80
    - host: www.kuberbank.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kuberbank-frontend-service
                port:
                  number: 80
